---
- hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: git
        state: present

    - name: Install Docker
      shell:  curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

    - name: Start Docker
      shell: service docker start

    - name: Stop running containers
      shell: |
        containers=$(docker ps -q)
        if [ ! -z $containers ]; then
          docker kill $containers;
        fi
        
        containers=$(docker ps -a -q)
        if [ ! -z $containers ]; then
          docker rm $containers;
        fi

    - name: Delete old app files
      file:
        state: absent
        path: /app

    - name: Clone repository
      git:
        repo: https://github.com/TastyLabs/TastyLabs
        dest: /app

    - name: Start application
      shell: cd /app && docker-compose up -d --build --remove-orphans
