---
- hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install docker-ce docker-ce-cli containerd.io

    - name: Install docker-compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Start Docker
      shell: service docker start

    - name: Stop running containers
      shell: |
        containers=$(docker ps -q)
        if [ ! -z $containers ]; then
          docker kill $containers;
        fi
        
        containers=$(docker ps -a -q)
        if [ ! -z $containers ]; then
          docker rm $containers;
        fi

    - name: Delete old app files
      file:
        state: absent
        path: /app

    - name: Clone repository
      git:
        repo: https://github.com/TastyLabs/TastyLabs
        dest: /app

    - name: Start application
      shell: cd /app && docker-compose up -d --build --remove-orphans
